"""Added metrics table

Revision ID: 112905df90a3
Revises: 0e3bfe71a6b3
Create Date: 2025-10-15 00:36:54.176255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112905df90a3'
down_revision: Union[str, Sequence[str], None] = '0e3bfe71a6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_ver', sa.String(), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('precision', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('recall', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('f1', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_created_at'), 'metrics', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_created_at'), table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
