services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - ml
    restart: unless-stopped

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
